services:
  db:
    build: ./database
    container_name: latteshub_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT_EXTERNAL}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  hop:
    image: apache/hop:latest
    container_name: lattes_hub_etl
    depends_on:
      - db
    profiles:
      - etl
    volumes:
      - ./database/apache_hop:/project
      - ./database/data:/project/data
    environment:
      - HOP_PROJECT_FOLDER=/project
      - HOP_PROJECT_NAME=LattesHub
      - HOP_FILE_PATH=/project/metadata/workflows/workflow_master.hwf
      - HOP_RUN_CONFIG=local
      - HOP_LOG_LEVEL=Basic
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  backend:
    build: ./backend
    container_name: latteshub_backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  pg_data:
